In [1]:
import pandas as pd

In [7]:
excel = pd.ExcelFile('monthly-may.xlsx')

In [10]:
monthly_excel = excel.parse(excel.sheet_names[0])

In [11]:
monthly_excel

                                                                                                            CURRENT MONTH  \
Income Statement Information NaN                                                                                      NaN
NaN                          NaN                                                                                      NaN
                             $  Sales by top customers                                                                NaN
                             NaN                                                                               Customer A
                             NaN                                                                               Customer B
                             NaN                                                                               Customer C
                             NaN                                                                               Customer D
                             NaN                                                                               Customer E
                             NaN                                                                      All Other Customers
                             NaN                                                                              Total Sales
                             NaN                                                                                      NaN
                             $ Sales projections for 6 M out                                                          NaN
                             NaN                                                                                      NaN
                             NaN                                                                                      NaN
                             Cost of Goods Sold                                                                       NaN
                             NaN                                                                                      NaN
                             Payroll Costs                                                                            NaN
                             NaN                                                                                      NaN
                             Rent/ Leases                                                                             NaN
                             NaN                                                                                      NaN
                             Sales, General & Administrative                                                          NaN
                             NaN                                                                                      NaN
                             Other & Miscellaneous                                                                    NaN
                             Other #2 ______________                                                                  NaN
                             NaN                                                                                      NaN
                             EBIT                                                                                     NaN
                             NaN                                                                                      NaN
                             Interest Expense                                                                         NaN
Rate                         NaN                                                                                      NaN
0.25                         Taxes                                                                                    NaN
NaN                          NaN                                                                                      NaN
                             Net Income                                                                               NaN
                             NaN                                                                      Net Profit Margin %
                             NaN                                                                                      NaN
                             NaN                                                                                      NaN
PRODUCTION INFORMATION       NaN                                                                                      NaN
NaN                          NaN                                                                              in UNITS!!!
                             + Ending Inventory / - Outstanding Orders                                                NaN
                             NaN                                        If Pos Beginning inventory/ If Neg (Outstandin...
                             NaN                                                              # Made (Added to inventory)
                             NaN                                                          # Sold (removed from inventory)
                             NaN                                                  + Ending Inventory/ -Outstanding Orders

                                                                        Unnamed: 1  \
Income Statement Information NaN                                               NaN
NaN                          NaN                                               NaN
                             $  Sales by top customers                         NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             $ Sales projections for 6 M out                   NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             Cost of Goods Sold                                NaN
                             NaN                                               NaN
                             Payroll Costs                                     NaN
                             NaN                                               NaN
                             Rent/ Leases                                      NaN
                             NaN                                               NaN
                             Sales, General & Administrative                   NaN
                             NaN                                               NaN
                             Other & Miscellaneous                             NaN
                             Other #2 ______________                           NaN
                             NaN                                               NaN
                             EBIT                                              NaN
                             NaN                                               NaN
                             Interest Expense                                  NaN
Rate                         NaN                                               NaN
0.25                         Taxes                                             NaN
NaN                          NaN                                               NaN
                             Net Income                                        NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
PRODUCTION INFORMATION       NaN                                               NaN
NaN                          NaN                                               NaN
                             + Ending Inventory / - Outstanding Orders         NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN

                                                                        Unnamed: 2  \
Income Statement Information NaN                                               NaN
NaN                          NaN                                               NaN
                             $  Sales by top customers                         NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             $ Sales projections for 6 M out                   NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             Cost of Goods Sold                                NaN
                             NaN                                               NaN
                             Payroll Costs                                     NaN
                             NaN                                               NaN
                             Rent/ Leases                                      NaN
                             NaN                                               NaN
                             Sales, General & Administrative                   NaN
                             NaN                                               NaN
                             Other & Miscellaneous                             NaN
                             Other #2 ______________                           NaN
                             NaN                                               NaN
                             EBIT                                              NaN
                             NaN                                               NaN
                             Interest Expense                                  NaN
Rate                         NaN                                               NaN
0.25                         Taxes                                             NaN
NaN                          NaN                                               NaN
                             Net Income                                        NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
PRODUCTION INFORMATION       NaN                                               NaN
NaN                          NaN                                               NaN
                             + Ending Inventory / - Outstanding Orders         NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                               NaN
                             NaN                                              25.0

                                                                        2018-05-01 00:00:00
Income Statement Information NaN                                                        NaN
NaN                          NaN                                                        NaN
                             $  Sales by top customers                                  NaN
                             NaN                                                  35.000000
                             NaN                                                 200.000000
                             NaN                                                  37.000000
                             NaN                                                  82.000000
                             NaN                                                  49.000000
                             NaN                                                 440.000000
                             NaN                                                 843.000000
                             NaN                                                        NaN
                             $ Sales projections for 6 M out                     950.000000
                             NaN                                                        NaN
                             NaN                                                        NaN
                             Cost of Goods Sold                                  400.000000
                             NaN                                                        NaN
                             Payroll Costs                                       100.000000
                             NaN                                                        NaN
                             Rent/ Leases                                         75.000000
                             NaN                                                        NaN
                             Sales, General & Administrative                      62.000000
                             NaN                                                        NaN
                             Other & Miscellaneous                                25.000000
                             Other #2 ______________                               0.000000
                             NaN                                                        NaN
                             EBIT                                                181.000000
                             NaN                                                        NaN
                             Interest Expense                                      5.000000
Rate                         NaN                                                        NaN
0.25                         Taxes                                                45.250000
NaN                          NaN                                                        NaN
                             Net Income                                          130.750000
                             NaN                                                   0.155101
                             NaN                                                        NaN
                             NaN                                                        NaN
PRODUCTION INFORMATION       NaN                                                        NaN
NaN                          NaN                                                        NaN
                             + Ending Inventory / - Outstanding Orders                  NaN
                             NaN                                                  25.000000
                             NaN                                                  10.000000
                             NaN                                                  15.000000
                             NaN                                                  20.000000

In [12]:
monthly_excel[0]

KeyError: 0